// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import "./globals.css";

import Link from "next/link";
import { Logo } from "@/components/icons";
import { DrawerLinks } from "@/components/layout/Drawer/DrawerContent";
import invoiceNavItems from "../nav-items/invoice";
import { MobileHeader } from "@/components/layout/Mobile/MobileHeader";

export const metadata = {
  title: "Glaucidae",
  description:
    "Automatic invoicing system for freelancers and small businesses.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-gray-50">
      <body>
        <div className="grid min-h-screen w-full lg:grid-cols-[280px_1fr]">
          <div className="hidden border-r bg-gray-100/40 lg:block dark:bg-gray-800/40">
            <div className="flex h-full max-h-screen flex-col gap-2">
              <div className="flex h-[60px] items-center border-b px-5">
                <Link
                  className="flex items-center gap-2 font-semibold"
                  href="/"
                >
                  <Logo />
                  <span className="">Glaucidae</span>
                </Link>
              </div>
              <div className="flex-1 overflow-auto py-2">
                <nav className="grid items-start px-4 text-sm font-medium">
                  <DrawerLinks NavigationItems={invoiceNavItems} />
                </nav>
              </div>
            </div>
          </div>
          <div className="flex flex-col">
            <MobileHeader />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
